services:
  - type: web
    name: laravel-backend
    env: docker
    plan: free
    dockerfilePath: ./dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/database/database.sqlite
      - key: CACHE_STORE
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: BACKEND_URL
        value: https://laravel-backend-zyy3.onrender.com/api
      - key: APP_URL
        value: https://laravel-backend-zyy3.onrender.com
      # WhatsApp Business API credentials - SET THESE IN RENDER DASHBOARD
      # DO NOT PUT REAL VALUES HERE - THIS FILE IS PUBLIC ON GITHUB
      - key: WHATSAPP_ACCESS_TOKEN
        sync: false  # Set manually in Render dashboard
      - key: WHATSAPP_PHONE_NUMBER_ID
        sync: false  # Set manually in Render dashboard  
      - key: WHATSAPP_BUSINESS_ACCOUNT_ID
        sync: false  # Set manually in Render dashboard
      - key: WHATSAPP_WEBHOOK_VERIFY_TOKEN
        sync: false  # Set manually in Render dashboard