services:
  - type: web
    name: laravel-backend
    env: docker
    plan: free
    dockerfilePath: ./dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: database/database.sqlite
      - key: BACKEND_URL
        value: https://laravel-backend-zyy3.onrender.com/api