services:
  - type: web
    name: laravel-whatsapp-bot
    env: docker
    plan: starter  # Free plan has limited resources, starter is better for WhatsApp bot
    dockerfilePath: ./dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/database/database.sqlite
      - key: NODE_ENV
        value: production
      - key: BACKEND_URL
        # This will be automatically set to your Render service URL
        sync: false
    disk:
      name: whatsapp-data
      mountPath: /var/www/whatsapp-session
      sizeGB: 1