services:
  - type: web
    name: laravel-backend
    env: php
    buildCommand: |
      composer install --no-dev
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /data/database.sqlite
    disk:
      name: sqlite-data
      mountPath: /data
      sizeGB: 1