services:
  - type: web
    name: laravel-backend
    env: docker
    plan: free
    dockerfilePath: ./dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: database/database.sqlite
      - key: BACKEND_URL
        value: https://laravel-backend-zyy3.onrender.com/api
      - key: APP_URL
        value: https://laravel-backend-zyy3.onrender.com
      - key: WHATSAPP_ACCESS_TOKEN
        value: EAAQexrfMnrgBPG9YusT9IhSj4CSephNqLsKJZC1evN2TOjKxJbujA4zCwm9NS6vocCzvAF9hWcMlLj4ZCHjGw2UiQaXmwAz7FiT9P1qYglvFM6bkf7YZBoh58ClTJDJisD1LUP2aIKMVZC2XYVZCKnm9fZBPSaUpI2LQ68H0zzVJ7IVY2UbmVOe2Hh8bFqkLrCRdSRZBz1CSRCFZBBvuXIKVTQ4hHWLZB0L22CViMch9mD1g30wZDZD
      - key: WHATSAPP_PHONE_NUMBER_ID
        value: 674311909107796
      - key: WHATSAPP_BUSINESS_ACCOUNT_ID
        value: 706999642168995
      - key: WHATSAPP_WEBHOOK_VERIFY_TOKEN
        value: webhook_verify_secure_123